export const Routes = {
  CreateForm: "/create/[type]",
  AuthForm: "/authentication/[mode]",
  EditFieldForm: "/profile/settings/editProfile/[key]",
  PostDetail: "/content/[id]",
  UserDetail: "/profile/[id]",
  Search: "/search/container",
  Settings: "/profile/settings/container",
  EditProfile: "/profile/settings/editProfile/container",
  EditPreferences: "/profile/settings/editPreferences/container",
  Onboarding: "/onboarding/container",
  Nutrition: "/content/posts/recipe/nutrition/container",
  ProfileTab: "/(tabs)/profile",
  Home: "/",
} as const;
