export const Routes = {
  CreateForm: "/create/[type]",
  AuthForm: "/authentication/[mode]",
  EditFieldForm: "/profile/settings/editProfile/[key]",
  PostDetail: "/content/[id]",
  UserDetail: "/profile/[id]",
  Search: "/search/container",
  Settings: "/profile/settings/container",
  History: "/profile/history/container",
  CommunityList: "/profile/communityList/container",
  Listing: "/planner/listing/container",
  EditProfile: "/profile/settings/editProfile/container",
  EditPreferencesForm: "/profile/settings/editPreferences/[key]",
  MealConfiguration: "/planner/mealConfig/container",
  Onboarding: "/onboarding/container",
  Nutrition: "/content/posts/recipe/nutrition/container",
  Rating: "/content/posts/recipe/rating/container",
  ProfileTab: "/(tabs)/profile",
  PlannerTab: "/(tabs)/planner",
  Home: "/",
} as const;
